// @generated by WebStorm Sequelize Plugin
/** @type {import('sequelize').QueryInterface} queryInterface */
/** @type {typeof import('sequelize')} Sequelize */

/**
 * Migration Template (ESM)
 * ---------------------------
 * This migration file was auto-generated by the WebStorm Sequelize Plugin.
 *
 * You can modify this file to define your migration logic.
 * Each migration consists of two asynchronous functions:
 *   - `up`: applies schema changes (e.g., creates tables, adds columns)
 *   - `down`: reverts those changes (e.g., drops tables)
 *
 */

export async function up(queryInterface, Sequelize) {
  // TODO: Write your forward migration logic here
}

export async function down(queryInterface, Sequelize) {
  // TODO: Write your rollback logic here
}
