// @generated by WebStorm Sequelize Plugin
/** @type {import('sequelize').QueryInterface} queryInterface */
/** @type {typeof import('sequelize')} Sequelize */

// Exemple :
// export async function up(queryInterface, Sequelize) {
//   await queryInterface.createTable('example_table', {
//     id: { type: Sequelize.UUID, defaultValue: Sequelize.literal('gen_random_uuid()'), primaryKey: true },
//     created_at: { type: Sequelize.DATE, allowNull: false, defaultValue: Sequelize.NOW },
//     updated_at: { type: Sequelize.DATE, allowNull: false, defaultValue: Sequelize.NOW }
//   });
// }
//
// export async function down(queryInterface, Sequelize) {
//   await queryInterface.dropTable('example_table');
// }

export async function up(queryInterface, Sequelize) {
  // TODO: écris ta migration ici
}

export async function down(queryInterface, Sequelize) {
  // TODO: rollback ici
}
