// @generated by WebStorm Sequelize Plugin
/** @type {import('sequelize').QueryInterface} queryInterface */
/** @type {typeof import('sequelize')} Sequelize */
'use strict';

// Exemple :
// module.exports = {
//   async up(queryInterface, Sequelize) {
//     await queryInterface.createTable('example_table', {
//       id: { type: Sequelize.UUID, defaultValue: Sequelize.literal('gen_random_uuid()'), primaryKey: true },
//       created_at: { type: Sequelize.DATE, allowNull: false, defaultValue: Sequelize.NOW },
//       updated_at: { type: Sequelize.DATE, allowNull: false, defaultValue: Sequelize.NOW }
//     });
//   },
//   async down(queryInterface, Sequelize) {
//     await queryInterface.dropTable('example_table');
//   }
// };

module.exports = {
  async up(queryInterface, Sequelize) {
    // TODO: écris ta migration ici
  },
  async down(queryInterface, Sequelize) {
    // TODO: rollback ici
  }
};
