// @generated by WebStorm Sequelize Plugin
/** @type {import('sequelize').QueryInterface} queryInterface */
/** @type {typeof import('sequelize')} Sequelize */
'use strict';

/**
 * Migration Template (CommonJS)
 * --------------------------------
 * This file was auto-generated by the WebStorm Sequelize Plugin.
 *
 * You can safely edit this file to define your migration logic.
 * Each migration consists of two main functions:
 *   - `up`: applies changes (e.g., creating tables, adding columns)
 *   - `down`: reverts them (e.g., dropping tables)
 *
 */

module.exports = {
  async up(queryInterface, Sequelize) {
    // TODO: Write your forward migration logic here
  },

  async down(queryInterface, Sequelize) {
    // TODO: Write your rollback logic here
  },
};
